# Generated by Django 2.2.12 on 2022-01-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='date',
            new_name='openDate',
        ),
        migrations.AddField(
            model_name='point',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='point',
            name='closeDate',
            field=models.DateField(null=True),
        ),
    ]
