# Generated by Django 2.2.12 on 2022-01-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_auto_20220116_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='closeDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
