# Generated by Django 4.1.1 on 2022-09-20 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_type', models.CharField(max_length=10)),
                ('registration', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vechicle_manu', models.TextField(default='None', max_length=150)),
                ('vehicle_model', models.TextField(default='None', max_length=150)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
